In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

## Task1

빈 칸을 채워주세요!

단계별 output이 github 파일에는 남아있으니 그 output과 동일한 형태인지 확인하면서 진행해주시면 됩니다~

In [2]:
#1. 생성할 문장 데이터

sentence = ("Brick walls are there for a reason and you must not think "
            "that the brick walls aren't there to keep us out, but rather "
            "in this way that the brick walls are there to show us how badly we want things.")

In [4]:
#2. 문자 집합 만들기
world_set = list(set(sentence))

## 문제(1): 각 문자에 정수 인코딩 (공백도 하나의 원소로 포함)
vocab = {c: i for i, c in enumerate(world_set)}

In [5]:
print(vocab)

{'b': 0, 't': 1, 'o': 2, 'w': 3, "'": 4, 'r': 5, ' ': 6, ',': 7, 'a': 8, 'n': 9, 'f': 10, 'c': 11, 'l': 12, 'B': 13, 'k': 14, 'y': 15, 'i': 16, 'h': 17, 'p': 18, 'u': 19, 'm': 20, '.': 21, 'g': 22, 's': 23, 'e': 24, 'd': 25}


In [6]:
#3. 문자 집합 크기 확인

vocab_size = len(vocab)
print('문자 집합 크기 : {}'.format(vocab_size))

문자 집합 크기 : 26


In [7]:
#4. 하이퍼 파라미터 설정(자유롭게 수정해보세요!)

hidden_size = vocab_size # 같아야 하는 것 확인!
sequence_length = 10  # 너무 길거나 너무 짧게 잡으면 안됩니다! #앞서 만든 샘플을 10개의 단위로 끊어서 샘플을 만드는 것
learning_rate = 0.01

In [8]:
#5. seqence 길이 단위 자르기

# 데이터 구성을 위한 리스트
x_data = []
y_data = []

## 문제(2): 반복문 내에서의 인덱싱을 사용하여 sequence_length 값 단위로 샘플을 잘라 데이터 만들기, y_str은 x_str은 한 칸씩 쉬프트된 sequnce

for i in range(0, len(sentence) - sequence_length):
  x_str = sentence[i:i + sequence_length] 
  y_str = sentence[i + 1: i + sequence_length + 1]
  print(i, x_str, "->", y_str)

  # x_str과 y_str이 문자집합에 해당하는 인덱스를 각각 x_data, y_data에 append
  x_data.append([vocab[c] for c in x_str])
  y_data.append([vocab[d] for d in y_str])

0 Brick wall -> rick walls
1 rick walls -> ick walls 
2 ick walls  -> ck walls a
3 ck walls a -> k walls ar
4 k walls ar ->  walls are
5  walls are -> walls are 
6 walls are  -> alls are t
7 alls are t -> lls are th
8 lls are th -> ls are the
9 ls are the -> s are ther
10 s are ther ->  are there
11  are there -> are there 
12 are there  -> re there f
13 re there f -> e there fo
14 e there fo ->  there for
15  there for -> there for 
16 there for  -> here for a
17 here for a -> ere for a 
18 ere for a  -> re for a r
19 re for a r -> e for a re
20 e for a re ->  for a rea
21  for a rea -> for a reas
22 for a reas -> or a reaso
23 or a reaso -> r a reason
24 r a reason ->  a reason 
25  a reason  -> a reason a
26 a reason a ->  reason an
27  reason an -> reason and
28 reason and -> eason and 
29 eason and  -> ason and y
30 ason and y -> son and yo
31 son and yo -> on and you
32 on and you -> n and you 
33 n and you  ->  and you m
34  and you m -> and you mu
35 and you mu -> nd you mus
36

In [9]:
# 출력해서 한 칸씩 쉬프트된 것 확인하기!

print(x_data[0]) #Brick wall
print(y_data[0]) #rick walls

[13, 5, 16, 11, 14, 6, 3, 8, 12, 12]
[5, 16, 11, 14, 6, 3, 8, 12, 12, 23]


In [10]:
##6. 입력 시퀀스에 대해 원핫인코딩 수행

## 문제(4) : x_data를 원핫인코딩 > numpy의 eye를 쓸 수 있지 않을까?
x_one_hot = [np.eye(vocab_size)[x] for x in x_data] #np.eye:(n x m)크기의 2차원 행렬을 만드는 함수

##7. 입력 데이터, 레이블데이터 텐서로 변환

## 문제(5) : x_one_hot과 y_data 텐서로 변환 : 둘 다 같은 형식의 텐서로 변환하면 될까?? (FloatTensor, LongTesor 중 맞는 것은?)
X = torch.FloatTensor(x_one_hot) 
Y = torch.LongTensor(y_data) 

#데이터 타입에 따라 텐서의 자료형 다름
 #floattensor - 32 bit floating point
 #longtensor - 64-bit integer

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  if __name__ == '__main__':


In [11]:
##8. 크기 확인
print('훈련 데이터의 크기 : {}'.format(X.shape))
print('레이블의 크기 : {}'.format(Y.shape))

훈련 데이터의 크기 : torch.Size([188, 10, 26])
레이블의 크기 : torch.Size([188, 10])


In [12]:
##9.원핫인코딩 결과 샘플 확인하기
print(X[0])

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0.,

In [13]:
##10. 레이블 데이터 샘플 확인하기
print(Y[0]) #rick walls

tensor([ 5, 16, 11, 14,  6,  3,  8, 12, 12, 23])


In [14]:
##11. RNN 모델 구현

##문제(6) : 기본 pytorch 인자 넣기 연습 + forward 채우기
### 조건 : rnn layer 2개 쌓기 + 마지막은 fc layer
### batch_fisrt 설정 필요할까? (유튜브 강의 참고)

class Net(torch.nn.Module):
  def __init__(self, input_dim, hidden_dim, layers):
    super(Net, self).__init__()
    self.rnn = torch.nn.RNN(input_dim, hidden_dim, num_layers=layers, batch_first=True) #num_layers: 쌓을 은닉층의 개수
    self.fc = torch.nn.Linear(hidden_dim, hidden_dim, bias=True)
  
  def forward(self, x):
    x, _status = self.rnn(x)
    x = self.fc(x)
    return x

In [15]:
net = Net(vocab_size, hidden_size, 2) #num_layers:2 -> 층 두개 

In [16]:
##12. loss function
criterion = torch.nn.CrossEntropyLoss() #비용함수 선언

##13. optimizer
optimizer = optim.Adam(net.parameters(), learning_rate) #옵티마이저 Adam 선언

In [17]:
##14. 출력 크기 점검
outputs = net(X) #3차원 텐서 
print(outputs.shape) #(배치 차원, 시점, 출력의 크기) = (188, 10, 26)

torch.Size([188, 10, 26])


In [18]:
##15. Training 시작

for i in range(100):
    optimizer.zero_grad()
    outputs = net(X) #(188, 10, 26) 크기를 가진 텐서를 매 epoch마다 모델의 입력으로 사용
    ##문제(7) : outputs, Y 형태 그대로 넣으면 안되죠. view 함수를 이용해 loss값을 계산해봅시다.
    loss = criterion(outputs.view(-1, vocab_size), Y.view(-1)) #2차원 텐서로 변환 #view를 이용해 배치 차원과 시점 차원을 하나로 만듦
    loss.backward()
    optimizer.step()

    #16. 예측결과 확인
    results = outputs.argmax(dim=2)
    predict_str = ""
    for j, result in enumerate(results):
        if j == 0: # 처음에는 예측 결과를 전부 가져오기
            predict_str += ''.join([world_set[t] for t in result])
        else: # 그 다음에는 마지막 글자만 반복 추가
            predict_str += world_set[result[-1]]

    print(predict_str)

iibiibibibiiiibiibbibiiimbiiibiiibmiiiiiimibbiibibibibbiibibiibibbiiibiibibibiiiibibibibbibiiibibiiiiiiibibmiiibibibbibiiiibbiiiiiiibiibibbiiibiibibibiiiibiibbibiiibiiibiiiiiibiiiibibibiiiiibibbiii
i     u        u     ua   u                         a     i    u         a          u i    u                           u  a    a   u    u         a        u     u                     a  a   ua     
u                                                                                                                                                                                                    
s                                                                                                                                                                                                    
                                                                                                                                                                                                     
          

In [19]:
predict_str

"rick walls are there tor a reason and you must not think that the brick walls are 't there to seep us out, but rather in this way that the brick walls are there to show us how badly we want thingsb"

결과가 어떤가요?? 마지막 에폭의 문장이 그럴싸한가요?

## Task2

위 sentence는 제가 임의로 생성한 문장들입니다.

마음에 드시는 문구 가져오셔서 문장이 어떻게 생성되는지 확인해보세요! 

영어가 아닌 한국어로 시도해보는 것도 좋겠죠? 

수정이 많이 필요(토큰화 등) 할 수 있으나 한번 시도해보시는 것 권장드립니다 :)

위 베이스라인은 어디든 수정하셔도 좋고 조금 더 자연스러운 문장이 나올 수 있게 다양한 시도를 해보세요!

조건 : 문장 3개 이상, 연결성이 있는 문장을 " " 으로 구분하여 ( )에 넣기

In [2]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git
%cd Mecab-ko-for-Google-Colab
!bash install_mecab-ko_on_colab190912.sh

fatal: destination path 'Mecab-ko-for-Google-Colab' already exists and is not an empty directory.
/content/Mecab-ko-for-Google-Colab
Installing konlpy.....
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2022-08-16 13:21:04--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c5:2ef4, 2406:da00:ff00::22c0:3470, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None&AWSAccessKeyId=ASIA6KOSE3BNB7DQI3K2&Signatur

In [4]:
#1. 생성할 문장 데이터

kor_text= ("나의 자라나는 마음을 못 본채 꺾어 버릴 수는 없네"
            "미련 남길바엔 그리워 아픈게 나아"
            "서둘러 안겨본 그 품은 따스할 테니")

In [ ]:
from konlpy.tag import Mecab, Okt

In [8]:
tokenizer = Okt()
word = tokenizer.morphs(kor_text)

In [9]:
print(word)

['나', '의', '자라나는', '마음', '을', '못', '본채', '꺾어', '버릴', '수', '는', '없네', '미련', '남길', '바', '엔', '그리워', '아픈게', '나아', '서둘러', '안겨', '본', '그', '품은', '따스할', '테', '니']


In [10]:
tokenizer = Mecab()
word  = tokenizer.morphs(kor_text)

In [11]:
print(word) #형태소 분류를 더 잘하는 Mecab 사용

['나', '의', '자라나', '는', '마음', '을', '못', '본', '채', '꺾', '어', '버릴', '수', '는', '없', '네', '미련', '남길', '바', '엔', '그리워', '아픈', '게', '나아서', '둘러', '안겨', '본', '그', '품', '은', '따스', '할', '테', '니']


In [13]:
#2. 문자 집합 만들기
world_set = list(set(kor_text))

## 문제(1): 각 문자에 정수 인코딩 (공백도 하나의 원소로 포함)
vocab = {c: i for i, c in enumerate(world_set)}

In [14]:
print(vocab)

{'미': 0, '없': 1, '은': 2, '리': 3, '수': 4, '바': 5, '게': 6, '겨': 7, '러': 8, '할': 9, '본': 10, '네': 11, '아': 12, '품': 13, '마': 14, '채': 15, '테': 16, ' ': 17, '엔': 18, '을': 19, '꺾': 20, '못': 21, '음': 22, '어': 23, '릴': 24, '워': 25, '의': 26, '자': 27, '픈': 28, '스': 29, '남': 30, '길': 31, '나': 32, '버': 33, '련': 34, '안': 35, '라': 36, '니': 37, '둘': 38, '서': 39, '그': 40, '는': 41, '따': 42}


In [15]:
#3. 문자 집합 크기 확인

vocab_size = len(vocab)
print('문자 집합 크기 : {}'.format(vocab_size))

문자 집합 크기 : 43


In [16]:
#4. 하이퍼 파라미터 설정

hidden_size = vocab_size 
sequence_length = 10
learning_rate = 0.01

In [18]:
#5. seqence 길이 단위 자르기

# 데이터 구성을 위한 리스트
x_data = []
y_data = []

for i in range(0, len(kor_text) - sequence_length):
  x_str = kor_text[i:i + sequence_length] 
  y_str = kor_text[i + 1: i + sequence_length + 1]
  print(i, x_str, "->", y_str)

  # x_str과 y_str이 문자집합에 해당하는 인덱스를 각각 x_data, y_data에 append
  x_data.append([vocab[c] for c in x_str])
  y_data.append([vocab[d] for d in y_str])

0 나의 자라나는 마음 -> 의 자라나는 마음을
1 의 자라나는 마음을 ->  자라나는 마음을 
2  자라나는 마음을  -> 자라나는 마음을 못
3 자라나는 마음을 못 -> 라나는 마음을 못 
4 라나는 마음을 못  -> 나는 마음을 못 본
5 나는 마음을 못 본 -> 는 마음을 못 본채
6 는 마음을 못 본채 ->  마음을 못 본채 
7  마음을 못 본채  -> 마음을 못 본채 꺾
8 마음을 못 본채 꺾 -> 음을 못 본채 꺾어
9 음을 못 본채 꺾어 -> 을 못 본채 꺾어 
10 을 못 본채 꺾어  ->  못 본채 꺾어 버
11  못 본채 꺾어 버 -> 못 본채 꺾어 버릴
12 못 본채 꺾어 버릴 ->  본채 꺾어 버릴 
13  본채 꺾어 버릴  -> 본채 꺾어 버릴 수
14 본채 꺾어 버릴 수 -> 채 꺾어 버릴 수는
15 채 꺾어 버릴 수는 ->  꺾어 버릴 수는 
16  꺾어 버릴 수는  -> 꺾어 버릴 수는 없
17 꺾어 버릴 수는 없 -> 어 버릴 수는 없네
18 어 버릴 수는 없네 ->  버릴 수는 없네미
19  버릴 수는 없네미 -> 버릴 수는 없네미련
20 버릴 수는 없네미련 -> 릴 수는 없네미련 
21 릴 수는 없네미련  ->  수는 없네미련 남
22  수는 없네미련 남 -> 수는 없네미련 남길
23 수는 없네미련 남길 -> 는 없네미련 남길바
24 는 없네미련 남길바 ->  없네미련 남길바엔
25  없네미련 남길바엔 -> 없네미련 남길바엔 
26 없네미련 남길바엔  -> 네미련 남길바엔 그
27 네미련 남길바엔 그 -> 미련 남길바엔 그리
28 미련 남길바엔 그리 -> 련 남길바엔 그리워
29 련 남길바엔 그리워 ->  남길바엔 그리워 
30  남길바엔 그리워  -> 남길바엔 그리워 아
31 남길바엔 그리워 아 -> 길바엔 그리워 아픈
32 길바엔 그리워 아픈 -> 바엔 그리워 아픈게
33 바엔 그리워 아픈게 -> 엔 그리워 아픈게 
34 엔 그리워 아픈게  ->  그리워 아픈게 나
35  그리워 아픈게 나 -> 그리워 아픈게 나아
36

In [19]:
#쉬프트 확인

print(x_data[0]) #Brick wall
print(y_data[0]) #rick walls

[32, 26, 17, 27, 36, 32, 41, 17, 14, 22]
[26, 17, 27, 36, 32, 41, 17, 14, 22, 19]


In [20]:
##6. 입력 시퀀스에 대해 원핫인코딩 수행

x_one_hot = [np.eye(vocab_size)[x] for x in x_data] 
##7. 입력 데이터, 레이블데이터 텐서로 변환

## x_one_hot과 y_data 텐서로 변환 
X = torch.FloatTensor(x_one_hot) 
Y = torch.LongTensor(y_data) 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  import sys


In [21]:
##8. 크기 확인
print('훈련 데이터의 크기 : {}'.format(X.shape))
print('레이블의 크기 : {}'.format(Y.shape))

훈련 데이터의 크기 : torch.Size([55, 10, 43])
레이블의 크기 : torch.Size([55, 10])


In [22]:
##9.원핫인코딩 결과 샘플 확인하기
print(X[0])

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 0.],


In [23]:
##10. 레이블 데이터 샘플 확인하기
print(Y[0]) 

tensor([26, 17, 27, 36, 32, 41, 17, 14, 22, 19])


In [24]:
##11. RNN 모델 구현

class Net(torch.nn.Module):
  def __init__(self, input_dim, hidden_dim, layers):
    super(Net, self).__init__()
    self.rnn = torch.nn.RNN(input_dim, hidden_dim, num_layers=layers, batch_first=True) #num_layers: 쌓을 은닉층의 개수
    self.fc = torch.nn.Linear(hidden_dim, hidden_dim, bias=True)
  
  def forward(self, x):
    x, _status = self.rnn(x)
    x = self.fc(x)
    return x

In [25]:
net = Net(vocab_size, hidden_size, 2) 

In [26]:
##12. loss function
criterion = torch.nn.CrossEntropyLoss() 

##13. optimizer
optimizer = optim.Adam(net.parameters(), learning_rate) 

In [27]:
##14. 출력 크기 점검
outputs = net(X) #3차원 텐서 
print(outputs.shape) 

torch.Size([55, 10, 43])


In [28]:
##15. Training 시작

for i in range(100):
    optimizer.zero_grad()
    outputs = net(X) #(188, 10, 26) 크기를 가진 텐서를 매 epoch마다 모델의 입력으로 사용
    ##문제(7) : outputs, Y 형태 그대로 넣으면 안되죠. view 함수를 이용해 loss값을 계산해봅시다.
    loss = criterion(outputs.view(-1, vocab_size), Y.view(-1)) #2차원 텐서로 변환 #view를 이용해 배치 차원과 시점 차원을 하나로 만듦
    loss.backward()
    optimizer.step()

    #16. 예측결과 확인
    results = outputs.argmax(dim=2)
    predict_str = ""
    for j, result in enumerate(results):
        if j == 0: # 처음에는 예측 결과를 전부 가져오기
            predict_str += ''.join([world_set[t] for t in result])
        else: # 그 다음에는 마지막 글자만 반복 추가
            predict_str += world_set[result[-1]]

    print(predict_str)

아을을미워마미꺾을을그을미을워워을미을워미을꺾을워워워미을꺾을을미미을워을미미을미을마을미미꺾워을을미바을워을을미을을겨을미꺾아
아    아     그     아                          아        그         아
아                                                               
                                                                
                                                                
                                                                
                                                                
                                                                
  그    그는  그       그는 그는 그는   그    그   그         그   그    그   그 
  그는   그는  그 그  그어 그는 그는 그는   남    그는  그픈  그  그러 그   그는그  그는  그는
  그는 아 그는  그 그   어 그는 그는 그는   남 그  그리본 그픈본 그  그러 그 본 그리그  그는  그는
  그 본아 그리  그 그 본 어 그는 그는 그는   그 그  그리본 그리본 그  그러 그 본 그 그  그리  그리
  그 본아 그리  못 그는 그어 그는 그는 그는   그 본는 그리워 그리본 그  그러 그 본 그 그  그리  그리
  그리 아 그는  못 그는 그는 그는 그는 그는   그 본는 그리워 그픈게 본  그러 그 본 그 그는 그리  그겨
  그리 아 그리워 못 본는 없어 그는 그는 그는   못 본는 그리워 그픈워 본  그러 그 본 본 그픈 그리워 그겨
  그리본는 그리워 못 그는 없어 그는 그는 

In [29]:
predict_str

'아 자라나는 마음을 못 본채 꺾어 버릴 수는 없네미련 남길바엔 그리워 아픈게 나아서둘러 안겨본 그 품은 따스할 테니'