## Task1

빈 칸을 채워주세요!

단계별 output이 github 파일에는 남아있으니 그 output과 동일한 형태인지 확인하면서 진행해주시면 됩니다~

In [2]:
#1. 생성할 문장 데이터

sentence = ("Brick walls are there for a reason and you must not think "
            "that the brick walls aren't there to keep us out, but rather "
            "in this way that the brick walls are there to show us how badly we want things.")

In [8]:
#2. 문자 집합 만들기
world_set = list(set(sentence))

## 문제(1): 각 문자에 정수 인코딩 (공백도 하나의 원소로 포함)
vocab = {i:j for j, i in enumerate(world_set)}

In [9]:
print(vocab)

{'y': 0, 'p': 1, 'd': 2, 'u': 3, 'e': 4, 'h': 5, 'b': 6, 'n': 7, 'g': 8, 'f': 9, 'B': 10, 's': 11, 'm': 12, 't': 13, "'": 14, 'r': 15, 'w': 16, ',': 17, 'k': 18, 'c': 19, 'a': 20, 'l': 21, ' ': 22, '.': 23, 'o': 24, 'i': 25}


In [12]:
#3. 문자 집합 크기 확인

vocab_size = len(vocab)
print('문자 집합 크기 : {}'.format(vocab_size))

문자 집합 크기 : 26


In [13]:
#4. 하이퍼 파라미터 설정(자유롭게 수정해보세요!)

hidden_size = vocab_size # 같아야 하는 것 확인!
sequence_length = 10  # 너무 길거나 너무 짧게 잡으면 안됩니다!
learning_rate = 0.01

In [14]:
#5. seqence 길이 단위 자르기

# 데이터 구성을 위한 리스트
x_data = []
y_data = []

## 문제(2): 반복문 내에서의 인덱싱을 사용하여 sequence_length 값 단위로 샘플을 잘라 데이터 만들기, y_str은 x_str은 한 칸씩 쉬프트된 sequnce

for i in range(0, len(sentence) - sequence_length):
  x_str = sentence[i:sequence_length+i]
  y_str = sentence[i+1:sequence_length+i+1]
  print(i, x_str, "->", y_str)

  # x_str과 y_str이 문자집합에 해당하는 인덱스를 각각 x_data, y_data에 append
  x_data.append([vocab[c] for c in x_str])
  y_data.append([vocab[d] for d in y_str])

0 Brick wall -> rick walls
1 rick walls -> ick walls 
2 ick walls  -> ck walls a
3 ck walls a -> k walls ar
4 k walls ar ->  walls are
5  walls are -> walls are 
6 walls are  -> alls are t
7 alls are t -> lls are th
8 lls are th -> ls are the
9 ls are the -> s are ther
10 s are ther ->  are there
11  are there -> are there 
12 are there  -> re there f
13 re there f -> e there fo
14 e there fo ->  there for
15  there for -> there for 
16 there for  -> here for a
17 here for a -> ere for a 
18 ere for a  -> re for a r
19 re for a r -> e for a re
20 e for a re ->  for a rea
21  for a rea -> for a reas
22 for a reas -> or a reaso
23 or a reaso -> r a reason
24 r a reason ->  a reason 
25  a reason  -> a reason a
26 a reason a ->  reason an
27  reason an -> reason and
28 reason and -> eason and 
29 eason and  -> ason and y
30 ason and y -> son and yo
31 son and yo -> on and you
32 on and you -> n and you 
33 n and you  ->  and you m
34  and you m -> and you mu
35 and you mu -> nd you mus
36

In [15]:
# 출력해서 한 칸씩 쉬프트된 것 확인하기!

print(x_data[0])
print(y_data[0])

[10, 15, 25, 19, 18, 22, 16, 20, 21, 21]
[15, 25, 19, 18, 22, 16, 20, 21, 21, 11]


In [39]:
##6. 입력 시퀀스에 대해 원핫인코딩 수행

## 문제(4) : x_data를 원핫인코딩 > numpy의 eye를 쓸 수 있지 않을까?
x_one_hot = [np.eye(vocab_size)[i] for i in x_data]

##7. 입력 데이터, 레이블데이터 텐서로 변환

## 문제(5) : x_one_hot과 y_data 텐서로 변환 : 둘 다 같은 형식의 텐서로 변환하면 될까?? (FloatTensor, LongTesor 중 맞는 것은?)
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ../torch/csrc/utils/tensor_new.cpp:201.)
  if __name__ == '__main__':


In [40]:
##8. 크기 확인
print('훈련 데이터의 크기 : {}'.format(X.shape))
print('레이블의 크기 : {}'.format(Y.shape))

훈련 데이터의 크기 : torch.Size([188, 10, 26])
레이블의 크기 : torch.Size([188, 10])


In [41]:
##9.원핫인코딩 결과 샘플 확인하기
print(X[0])

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0.,

In [42]:
##10. 레이블 데이터 샘플 확인하기
print(Y[0])

tensor([15, 25, 19, 18, 22, 16, 20, 21, 21, 11])


In [43]:
##11. RNN 모델 구현

##문제(6) : 기본 pytorch 인자 넣기 연습 + forward 채우기
### 조건 : rnn layer 2개 쌓기 + 마지막은 fc layer
### batch_fisrt 설정 필요할까? (유튜브 강의 참고)

class Net(torch.nn.Module):
  def __init__(self, input_dim, hidden_dim, layers):
    super(Net, self).__init__()
    self.rnn = torch.nn.RNN(input_dim, hidden_dim, layers, batch_first=True)
    self.fc = torch.nn.Linear(hidden_dim, vocab_size)
  
  def forward(self, x):
    x, hidden = self.rnn(x)
    x = self.fc(x)
    return x

In [44]:
net = Net(vocab_size, hidden_size, 2)

In [45]:
##12. loss function
criterion = torch.nn.CrossEntropyLoss()

##13. optimizer
optimizer = optim.Adam(net.parameters(), learning_rate)

In [46]:
##14. 출력 크기 점검
outputs = net(X)
print(outputs.shape)

torch.Size([188, 10, 26])


In [57]:
##15. Training 시작

for i in range(100):
    optimizer.zero_grad()
    outputs = net(X)
    ##문제(7) : outputs, Y 형태 그대로 넣으면 안되죠. view 함수를 이용해 loss값을 계산해봅시다.
    loss = criterion(outputs.view(-1, vocab_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    #16. 예측결과 확인
    results = outputs.argmax(dim=2)
    predict_str = ""
    for j, result in enumerate(results):
        if j == 0: # 처음에는 예측 결과를 전부 가져오기
            predict_str += ''.join([world_set[t] for t in result])
        else: # 그 다음에는 마지막 글자만 반복 추가
            predict_str += world_set[result[-1]]

    print(predict_str)

                                                  l                                                                                                                                                  
                                                                                                                                                                                                     
                                                                                                                                                                                                     
                                                                                                                                                                                                     
                                                                                                                                                                                                     
          

In [58]:
predict_str

"rick walls are there tor a reason and you must not think that the brick walls are 't there to keep us out, but rather in this way that the brick walls are there to khow us how badly we want thinks'"

결과가 어떤가요?? 마지막 에폭의 문장이 그럴싸한가요?

## Task2

위 sentence는 제가 임의로 생성한 문장들입니다.

마음에 드시는 문구 가져오셔서 문장이 어떻게 생성되는지 확인해보세요! 

영어가 아닌 한국어로 시도해보는 것도 좋겠죠? 

수정이 많이 필요(토큰화 등) 할 수 있으나 한번 시도해보시는 것 권장드립니다 :)

위 베이스라인은 어디든 수정하셔도 좋고 조금 더 자연스러운 문장이 나올 수 있게 다양한 시도를 해보세요!

조건 : 문장 3개 이상, 연결성이 있는 문장을 " " 으로 구분하여 ( )에 넣기

In [63]:
sentence = ("The idea of eternal return is a mysterious one. "
"And Nietzsche has often perplexed other philosophers with it. "
"To think that everything recurs as we once experienced it. "
"And that the recurrence itself recurs ad infinitum! "
"What does this mad myth signify? ")


In [66]:
world_set = sorted(list(set(sentence)))  
vocab = {word : index for index, word in enumerate(world_set)}

print(vocab)

{' ': 0, '!': 1, '.': 2, '?': 3, 'A': 4, 'N': 5, 'T': 6, 'W': 7, 'a': 8, 'c': 9, 'd': 10, 'e': 11, 'f': 12, 'g': 13, 'h': 14, 'i': 15, 'k': 16, 'l': 17, 'm': 18, 'n': 19, 'o': 20, 'p': 21, 'r': 22, 's': 23, 't': 24, 'u': 25, 'v': 26, 'w': 27, 'x': 28, 'y': 29, 'z': 30}


In [67]:
vocab_size = len(vocab)
print('문자 집합 크기 : {}'.format(vocab_size))

문자 집합 크기 : 31


In [68]:
# 하이퍼 파라미터
hidden_size = vocab_size 
sequence_length = 10
learning_rate = 0.01

In [69]:
# 데이터 구성을 위한 리스트
x_data = []
y_data = []

for i in range(0, len(sentence) - sequence_length):
  x_str = sentence[i:i+sequence_length]
  y_str = sentence[i+1: i+sequence_length+1]
  print(i, x_str, "->", y_str)

  # x_str과 y_str이 문자집합에 해당하는 인덱스를 각각 x_data, y_data에 append
  x_data.append([vocab[c] for c in x_str])
  y_data.append([vocab[d] for d in y_str])

0 The idea o -> he idea of
1 he idea of -> e idea of 
2 e idea of  ->  idea of e
3  idea of e -> idea of et
4 idea of et -> dea of ete
5 dea of ete -> ea of eter
6 ea of eter -> a of etern
7 a of etern ->  of eterna
8  of eterna -> of eternal
9 of eternal -> f eternal 
10 f eternal  ->  eternal r
11  eternal r -> eternal re
12 eternal re -> ternal ret
13 ternal ret -> ernal retu
14 ernal retu -> rnal retur
15 rnal retur -> nal return
16 nal return -> al return 
17 al return  -> l return i
18 l return i ->  return is
19  return is -> return is 
20 return is  -> eturn is a
21 eturn is a -> turn is a 
22 turn is a  -> urn is a m
23 urn is a m -> rn is a my
24 rn is a my -> n is a mys
25 n is a mys ->  is a myst
26  is a myst -> is a myste
27 is a myste -> s a myster
28 s a myster ->  a mysteri
29  a mysteri -> a mysterio
30 a mysterio ->  mysteriou
31  mysteriou -> mysterious
32 mysterious -> ysterious 
33 ysterious  -> sterious o
34 sterious o -> terious on
35 terious on -> erious one
36

In [71]:
len(x_data)

244

In [72]:
x_one_hot = [np.eye(vocab_size)[i] for i in x_data]

X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

In [73]:
print('훈련 데이터의 크기 : {}'.format(X.shape))
print('레이블의 크기 : {}'.format(Y.shape))

훈련 데이터의 크기 : torch.Size([244, 10, 31])
레이블의 크기 : torch.Size([244, 10])


In [74]:
print(X[0])

tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],

In [75]:
print(Y[0])

tensor([14, 11,  0, 15, 10, 11,  8,  0, 20, 12])


In [76]:
class Net(torch.nn.Module):
  def __init__(self, input_dim, hidden_dim, layers):
    super(Net, self).__init__()
    self.rnn = torch.nn.RNN(input_dim, hidden_dim, layers, batch_first=True)
    self.fc = torch.nn.Linear(hidden_dim, vocab_size)
  
  def forward(self, x):
    x, hidden = self.rnn(x)
    x = self.fc(x)
    return x

In [77]:
net = Net(vocab_size, hidden_size, 2)

In [78]:
##12. loss function
criterion = torch.nn.CrossEntropyLoss()

##13. optimizer
optimizer = optim.Adam(net.parameters(), learning_rate)

In [79]:
##14. 출력 크기 점검
outputs = net(X)
print(outputs.shape)

torch.Size([244, 10, 31])


In [80]:
##15. Training 시작

for i in range(100):
    optimizer.zero_grad()
    outputs = net(X)
    ##문제(7) : outputs, Y 형태 그대로 넣으면 안되죠. view 함수를 이용해 loss값을 계산해봅시다.
    loss = criterion(outputs.view(-1, vocab_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    #16. 예측결과 확인
    results = outputs.argmax(dim=2)
    predict_str = ""
    for j, result in enumerate(results):
        if j == 0: # 처음에는 예측 결과를 전부 가져오기
            predict_str += ''.join([world_set[t] for t in result])
        else: # 그 다음에는 마지막 글자만 반복 추가
            predict_str += world_set[result[-1]]

    print(predict_str)

WWWWvWvWWWWWWrvWkWtWWWvvWWWkvWvtvtvvvWkrWvWvWWWWWWWWkWkrkWkWkWWWtWvWWkWWtWWkWrWWWWkWWWWWkWWtvWWkWkWWkvWvWWkrvWWtWvtWrWWvtWtWWkWWWvWWrWWWtrWWWWvtWvvWvWkWWvWkWWkkWkWWWktvWWWWWvtWtWvtWWWkrWWWkvWWWkrvWWtWWkkWWWWvWWkvWWvWrvWWWkWWtWWrWWkvtWtWvWtWWtvvWvWtvktWk
ettttttttttttttdttttttttdttttttttttttdtttdttdttttdtttttttdttttttttttttdtttttttttttttttttdttttttttttttttttttttttttdttttttttttdttttttttttttttttttdttdttdttttxtttttttttttttttdttttttttttttttttttdtttttt.tttttttttttttttttttttvttttttttttdttttttttttttttttttvtttd
etttttt tttttttttt ttttttttt ttttttot ttt tt ttttttttttttttttttt ttttttttttttttttttttttttttttttttttttt ttottttttttttttttttttttt ttttttttttttttt tt tttttttttttttttttttttttttttttttttttttttttt tttttt ttttttttttt tttttttttttttttttttt ttttttt tttttttt tttttt
ett                                        t   tt             t   t    t               t                                        t                   t               t    t                       t                          t         t     t 

In [81]:
predict_str

'oe idea of eternal return is a mysterious one. And Nietzsche has often perplexed other philosophers with it. To think that everything recurs ad we once experienced it. And that the recurrence itself recurs as infinitum! What does this mad myth signify? '